[WIP][DCOS-16095] Handle 404 response from Admin Router while waiting for Metronome ser…
mesosphere/dcos-test-utils pull request #30
Opened 2017-06-07 22:20 UTC by adamtheturtle

…vice.

See https://jira.mesosphere.com/browse/DCOS-16095 - Integration tests: adjust _wait_for_metronome to Admin Router's service endpoint emitting 404 responses

### Testing

I will manually test this now. The PR is marked WIP until then.
I see that there is `dcos_test_utils/test_dcos_api_session.py` but it appears that there isn't really a way to test this easily.
I would appreciate feedback on whether and how to add direct tests for this.

2017-06-07 23:27 UTC, adamtheturtle commented
@mellenburg and @jgehrcke - This is marked as WIP as I have yet to manually test it. However, if it is urgent and I am asleep, feel free to take a look.

2017-06-08 01:45 UTC, adamtheturtle commented
I annoyingly have failed to hit this race in my manual testing. I would appreciate a review and guidance on whether and how to test.

2017-06-08 02:39 UTC, adamtheturtle commented
I reproduced this, and the fix seems to work. It showed the following a few times before moving on:

```
DEBUG:urllib3.connectionpool:https://172.17.0.2:443 "GET /service/metronome/v1/jobs HTTP/1.1" 404 None
INFO:dcos_test_utils.dcos_api_session:It may be the case that Admin Router is returning a 404 despite the Metronome service existing because it uses a cache. This cache is updated periodically.
```

2017-06-08 08:20 UTC, mhrabovcin approved these changes

2017-06-08 11:39 UTC, jgehrcke commented
Thank you, Adam. Let's hold this back for a while until we make progress on DCOS-16108 (sorry, still big thanks for your patch, good solution to the logging challenge!).

2017-06-09 16:20 UTC, vespian reviewed
I wonder if we shouldn't merge it now, as pinpointing DCOS-16108 make take us some time. I run into this error again today: https://teamcity.mesosphere.io/viewLog.html?buildId=678784&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_LaunchAzureResourceMana&tab=buildLog

Thanks for taking care of it @adamtheturtle !

2017-06-09 16:20 UTC, vespian commented on dcos_test_utils/dcos_api_session.py
> +            404: ('It may be the case that Admin Router is returning a 404 '
Possible error codes:
503 - cache is borked, this means that Marathon or Mesos are not up yet, continue waiting
404 - metronome has not registered with Mesos yet, continue waiting
502,504 - metronome has registered with mesos, but for some reason, the leading process is not responding, we may want to treat it as an error as I am not sure what can cause such a state. We probably discuss it a bit.
500 - I do not think this should be a valid state anymore, earlier this was ARs way of saying 404 but it is fixed now.

Hope it helps.

2017-06-09 22:53 UTC, mellenburg commented
I like the error code messages to help debugging, but why would we want to except Adminrouter errors in the wait_for_metronome step? Wouldn't we want to instead make the `wait_for_adminrouter` function ( https://github.com/mesosphere/dcos-test-utils/blob/master/dcos_test_utils/dcos_api_session.py#L278 ) more robust?

2017-06-10 12:00 UTC, adamtheturtle commented
Maybe we should wait and replace this whole bunch of code with `docs-checks` if I understand the purpose of https://github.com/dcos/dcos/pull/1609/files.

2017-06-15 13:36 UTC, jgehrcke requested changes
@mellenburg 

>  but why would we want to except Adminrouter errors in the wait_for_metronome step?

The `wait_for_metronome` is a bad naming choice. The `/service/...` endpoint involves quite a bit of Admin Router logic (since the beginning of 2016) so this has always been tested here, too (implicitly). Now that logic changed a bit. I would like to keep the naming discussion out of the picture for now.

@adamtheturtle as of Pawel's last comment I would love to see the following behavior for all `5xx` responses: have a generic error message for `5xx` HTTP responses, and make sure that the response status code as well as the _body_ is logged in that case. The error/log message emitted by dcos-test-utils should then not make an attempt to explain the failure (as it likely is wrong or unprecise in some regard).

2017-06-15 13:38 UTC, jgehrcke commented
While DCOS-16108 is being worked on (takes a while, as Pawel pointed out) let's go ahead with this so that dcos-test-utils' wait routine can keep fulfilling its task.

2017-06-16 15:33 UTC, adamtheturtle commented on dcos_test_utils/dcos_api_session.py
> +            404: ('It may be the case that Admin Router is returning a 404 '
@jgehrcke @mellenburg Do you have thoughts on `502,504`?

2017-06-16 15:38 UTC, adamtheturtle commented
@mhrabovcin @jgehrcke @mellenburg @vespian - I hope that I have addressed comments adequately. As testing this isn't super easy, I'd appreciate a first glance by someone to confirm that this is worth testing.

2017-06-16 15:39 UTC, adamtheturtle commented
Also see Pawel's request for discussion on https://github.com/mesosphere/dcos-test-utils/pull/30#discussion_r121166012.

2017-06-16 15:47 UTC, jgehrcke commented on dcos_test_utils/dcos_api_session.py
> +            log.info(r.content.decode())
Is that different from `r.text`?

2017-06-16 15:49 UTC, jgehrcke requested changes
As a quick improvement I'd love us to remove the error message in case of the 503 response, in line with my previous review:

> have a generic error message for 5xx HTTP responses

2017-06-16 15:49 UTC, jgehrcke commented on dcos_test_utils/dcos_api_session.py
> +            503: ('The cache is not working. This means that either Marathon '
I am not really convinced about the absolute correctness of this error message in all cases where Admin Router emits a 503. In such cases I _strongly_ favor having neutral error messages that have a low risk of providing false/misleading conclusions.

2017-06-16 15:50 UTC, adamtheturtle commented on dcos_test_utils/dcos_api_session.py
> +            503: ('The cache is not working. This means that either Marathon '
@jgehrcke Should I remove just 503 or other errors too?

2017-06-16 15:51 UTC, adamtheturtle commented on dcos_test_utils/dcos_api_session.py
> +            log.info(r.content.decode())
I saw that used elsewhere in this repository, but so is `r.text` so I have changed it.

2017-06-16 15:53 UTC, adamtheturtle commented
@jgehrcke - ah - I added the generic message for `5xx` errors, but kept the specific ones as well for those where (I thought) we knew the cause.

2017-06-16 15:54 UTC, adamtheturtle commented
Note that I removed support for 500, as per Pawel's comment.

2017-06-16 15:57 UTC, jgehrcke approved these changes
Nice! :rocket: :ship:

2017-06-16 15:58 UTC, jgehrcke commented
@mellenburg this should IMO be merged now.

2017-06-23 14:48 UTC, adamtheturtle commented
ping @mellenburg

2017-06-23 20:41 UTC, mellenburg commented
@adamtheturtle Sorry for not hearing the ping :grimacing: LGTM

2017-06-24 06:20 UTC, merged

2018-01-22 18:43 UTC, jgehrcke commented
What we missed here (CC @vespian) is that we did not emit debugging information in case `if r.status_code in expected_error_codes or r.status_code > 500:` was not `True`.