WIP: Add checks feature flag
mesosphere/dcos-test-utils pull request #32
Opened 2017-06-13 01:02 UTC by amitaekbote

2017-06-13 05:03 UTC, amitaekbote commented
@mellenburg ready for review, https://github.com/dcos/dcos/pull/1649 works fine with the change

2017-06-13 18:53 UTC, mellenburg requested changes

2017-06-13 18:53 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                    output = ssh_client.command(host, ['sudo', 'bash', 'dcos_node_upgrade.sh'], stdout="")
Why are you assigning stdout="" ?

2017-06-13 18:53 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                        raise Exception("Dont know whats going on here")
Please do not do this: You are remapping an exception to nothing. Doing nothing at all would expose the actual error whereas this explicitly obfuscates it

2017-06-13 18:53 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                    if returncode != 0:
If a CalledProcessError is raised then the error code MUST not be zero

2017-06-13 18:53 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                except CalledProcessError as e:
Why do we need to catch this at all?

2017-06-13 18:53 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                            'Timed out waiting for {} to rejoin the cluster after upgrade: {}'.
I don't see what makes this a timeout error specifically. How is nonzero guaranteed to be a timeout? Is there no other failure case?

2017-06-14 06:22 UTC, amitaekbote commented
"output": "",
      "status": 0
    }
  }
}
Node checks passed

[2017-06-13 23:20:35,755|dcos_test_utils.helpers|DEBUG]: Request method GET: http://52.41.209.145/. Arguments: {}
[2017-06-13 23:20:35,757|urllib3.connectionpool|DEBUG]: Starting new HTTP connection (1): 52.41.209.145
[2017-06-13 23:20:35,816|urllib3.connectionpool|DEBUG]: http://52.41.209.145:80 "GET / HTTP/1.1" 200 33526
[2017-06-13 23:20:35,845|dcos_test_utils.dcos_api_session|INFO]: Nginx is UP!
[2017-06-13 23:20:37,106|urllib3.connectionpool|DEBUG]: http://52.41.209.145:80 "GET /agent/93f3c592-487b-4fcd-8405-388b6919909e-S1/files/download?path=%2Fvar%2Flib%2Fmesos%2Fslave%2Fslaves%2F93f3c592-487b-4fcd-8405-388b6919909e-S1%2Fframeworks%2F93f3c592-487b-4fcd-8405-388b6919909e-0000%2Fexecutors%2Fupgrade-dns-31d1471409bc40939ec95ccf6b5f1b52.154a63d3-50c7-11e7-a399-3a12cc4b4ffe%2Fruns%2Fe323cb8b-54b4-4038-a39f-386eb5078ba2%2Fdns_resolve_log.txt HTTP/1.1" 200 32767
xfail

============== 1 passed, 1 xfailed, 1 xpassed in 2217.72 seconds ===============
___________________________________ summary ____________________________________
  py35-upgrade-test: commands succeeded
  congratulations :)

2017-06-14 07:03 UTC, amitaekbote commented
@mellenburg ready for another pass, works with flag in true or false state

2017-06-14 10:06 UTC, adamtheturtle commented on dcos_test_utils/upgrade.py
> +                        'Checks didnt pass, {} didnt rejoin the cluster after upgrade: {}'.
`s/didnt/didn't/g` (or `did not`).

2017-06-14 10:08 UTC, adamtheturtle commented on advanced_tests/test_upgrade.py
>  This test has 4 input parameters (set in the environment)
Is this title still correct? (maybe it was incorrect before?)

2017-06-14 17:08 UTC, amitaekbote commented
@adamtheturtle updated

2017-06-14 22:38 UTC, mellenburg requested changes
Fixing the invocation of the ssh_client to run the upgrade script is critical for collecting logs.

2017-06-14 22:38 UTC, mellenburg commented on advanced_tests/test_upgrade.py
> -WARNGING: This is a destructive process and you cannot go back
I is a much good typer

2017-06-14 22:38 UTC, mellenburg commented on advanced_tests/test_upgrade.py
> +    reason='TEST_UPGRADE_USE_CHECKS must be set in env to upgrade a cluster')
Nit: maybe default this to false, but better to be explicit than not so

2017-06-14 22:38 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +        use_checks: str) -> None:
Use a bool please

2017-06-14 22:38 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +            if use_checks == 'true':
`if use_checks:`

2017-06-14 22:38 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                except CalledProcessError as e:
There is no reason to catch a CalledProcessed error in this manner. Also, it is rarely advisable to raise a new exception from a different exception without using `raise from`. If your goal is to make sure you have access to this output, I would suggest the following:
```
log.info("Starting upgrade script on {host} ({role_name})...".format(host=host, role_name=role_name))
if use_checks:
    ssh_client.command(host, ['sudo', 'bash', 'dcos_node_upgrade.sh'], stdout=sys.stdout.buffer)
else:
    ssh_client. ... [keep it the same hereafter]
```

This is much more robust as you are going to get the stdout on the driver machine instantly whereas the current implementation only works when the process actually finishes (which is far from guaranteed in testing)

2017-06-14 22:38 UTC, mellenburg commented on advanced_tests/test_upgrade.py
> +        os.environ.get('TEST_UPGRADE_USE_CHECKS'))
This test is skipped if TEST_UPGRADE_USE_CHECKS is not in environ and we want this argument to be a bool so please do:
```
os.environ['TEST_UPGRADE_USE_CHECKS'] == 'true'
```

2017-06-14 22:59 UTC, mellenburg requested changes
remapping the error is not good, so please just remove that entire try/except clause. If you want to know which  host+role was just triggered, then use that log statement I suggested before calling the SSH client

2017-06-14 22:59 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +from subprocess import CalledProcessError
please remove

2017-06-14 22:59 UTC, mellenburg commented on dcos_test_utils/upgrade.py
> +                except CalledProcessError as e:
please remove

2017-06-15 00:05 UTC, amitaekbote commented
The upgrade test failed because of a bug during teardown, actual test is 💯

2017-06-15 00:07 UTC, mellenburg approved these changes

2017-06-15 00:07 UTC, mellenburg commented
Confirmed that failure is in fact due to a bug in the build configuration in CI, not this change at all. This is safe to promote to DC/OS testing now.

2017-06-15 00:08 UTC, merged